language: node_js
node_js:
  - "node"
install:
  - npm install
script:
  - npm run lint
before_deploy:
  - npm install -g now
deploy:
  provider: script
  script:
  - now --token=$NOW_TOKEN --public
  - now ln --token=$NOW_TOKEN
  on:
    all_branches: true
  skip_cleanup: true