language: node_js
node_js:
  - "node"
install:
  - npm install
script:
  - npm run lint
before_deploy:
  - npm install -g now
deploy:
  script:
  - now --token $NOW_TOKEN --public
  - now ln
  on:
    all_branches: true