language: node_js
node_js:
  - "node"
install:
  - yarn install
  - npm i -g now
script:
  - yarn lint
deploy:
  provider: script
  on:
    all_branches: true
  skip_cleanup: true
  script:
  - yarn deploy